### ISSUE TITLE
Allow interpolate the interface name in list connections command

### ISSUE THREAD

**Issue by bkmeneguello** [cardsurf/download-and-upload-speed#8]
I want to use NetHogs to list my connections, but it requires the interface name. Could it be made available to command string as placeholder?

**Comment by cardsurf** [comment]
It could be made available as an additional parameter. Since all of the applet settings are shown in a single window I would rather use an existing entry if it is possible to maintain readability.
I have created a bash script that runs `NetHogs` command with a name of a current network interface. To run the script:
1. Create a subfolder: `$HOME/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/scripts`
   Paste a script [run_nethogs.sh](https://github.com/cardsurf/download-and-upload-speed/files/1713467/run_nethogs.sh.zip) into the subfolder
   Grant executable permissons to the script
2. Open the applet configuration
   In the `Command` entry under the `Connections` section enter:
   `$HOME/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/scripts/run_nethogs.sh`
3. Left click on the applet to run the command
